### ISSUE TITLE
 alphanumeric charset limitation

### ISSUE THREAD

**Issue by ThisIsNotTheUserYouAreLookingFor** [Security-Onion-Solutions/securityonion-setup#3]
Hi, 

Is there a specific reason for the alphanumeric charset limitation on passwords?
after a bit of googling, seems related to sguil.
If you can point down why/where it is enforced I might be able to write a fix for it.

**Comment by dougburks** [comment]
Actually, I think this issue was related to ELSA and Snorby.  I believe the ELSA issue was resolved and Snorby is being removed, so we may be able to remove the alphanumeric requirement altogether.

**Comment by SkiTheSlicer** [comment]
I'm glad this was brought up, as I've been curious, too simce I'm able to add new users with special character passwords.

**Comment by dougburks** [comment]
Alphanumeric requirement removed:
https://github.com/Security-Onion-Solutions/securityonion-setup/commit/290cd6f378e0efe24f643c5565bb7ede31116542
