### ISSUE TITLE
several bugs in your setup script

### ISSUE THREAD

**Issue by kmahyyg** [Security-Onion-Solutions/securityonion-setup#47]
- Since you switched to systemd, but not change the `/dev/log` to correct location, you need to `sudo ln -sf /run/systemd/journal/dev-log /dev/log` to fix this problem.
- Docker package is unauthenticated due to unknown reason. Since you've used docker official repo, you may need to write a scirpt to authenticate and trust it first or directly add `--allow-unauthenticated` to your `$APT_OPTION` in `soup` script.

**Comment by kmahyyg** [comment]
Personally recommend upgrade to Ubuntu 18.04 LTS as quick as possible.

**Comment by dougburks** [comment]
Hi @kmahyyg ,

> * Since you switched to systemd, but not change the `/dev/log` to correct location, you need to `sudo ln -sf /run/systemd/journal/dev-log /dev/log` to fix this problem.

I'm not sure I understand.  I don't believe we've had any other feedback like this.  What was the exact problem that you were experiencing that led you to this?  Are you on a fresh installation or an upgrade from previous version?  If new installation, did you use our ISO image or another flavor of Ubuntu?

> * Docker package is unauthenticated due to unknown reason. Since you've used docker official repo, you may need to write a scirpt to authenticate and trust it first or directly add `--allow-unauthenticated` to your `$APT_OPTION` in `soup` script.

I'm not sure I understand this either.  `/usr/sbin/so-elastic-download` should install the necessary GPG key that Docker packages are signed with:
https://github.com/Security-Onion-Solutions/securityonion-elastic/blob/master/usr/sbin/so-elastic-download#L25
Perhaps that download failed in your environment due to firewall or other inline device?

> Personally recommend upgrade to Ubuntu 18.04 LTS as quick as possible.

We're currently working on our next generation platform which is code named Hybrid Hunter and will no longer be limited to just Ubuntu 16.04:
https://blog.securityonion.net/2019/10/security-onion-hybrid-hunter-111-alpha.html

**Comment by kmahyyg** [comment]
> I'm not sure I understand. I don't believe we've had any other feedback like this. What was the exact problem that you were experiencing that led you to this? Are you on a fresh installation or an upgrade from previous version? If new installation, did you use our ISO image or another flavor of Ubuntu?

Brand new installation within VMWare. But it just kept telling me that failed to start `syslog.socket` and I checked that it failed due to the systemd-journal listens at `/run/systemd/journald/dev-log` instead of `/run/systemd/journald/syslog`, and so on, `/dev/log` is not correctly listend due to this setting.

I also searched for this problem on google, some others said that we have to add `Alias=syslog.service` in `syslog-ng.service`. It definitely exists in the `syslog-ng.service` but I don't know why it won't work.

> I'm not sure I understand this either. /usr/sbin/so-elastic-download should install the necessary GPG key that Docker packages are signed with:
https://github.com/Security-Onion-Solutions/securityonion-elastic/blob/master/usr/sbin/so-elastic-download#L25
Perhaps that download failed in your environment due to firewall or other inline device?

I just run `sudo soup` after the finished all setup that `sosetup` asked me to do. Then get the `unauthenticated package` notification and so on `apt dist-upgrade` failed to execute in your `soup` script.

> We're currently working on our next generation platform which is code named Hybrid Hunter and will no longer be limited to just Ubuntu 16.04:
https://blog.securityonion.net/2019/10/security-onion-hybrid-hunter-111-alpha.html

Thanks for your work and reply.

**Comment by dougburks** [comment]
> Brand new installation within VMWare.

Did you install using our Security Onion ISO image or did you install some other flavor of Ubuntu and then add our software on top of that?

> I just run `sudo soup` after the finished all setup that `sosetup` asked me to do. Then get the `unauthenticated package` notification and so on `apt dist-upgrade` failed to execute in your `soup` script.

Do you have full outbound Internet access or do you have a firewall or some other device that is doing blocking and/or packet inspection?

**Comment by kmahyyg** [comment]
> Did you install using our Security Onion ISO image or did you install some other flavor of Ubuntu and then add our software on top of that?

**Comment by kmahyyg** [comment]
> Did you install using our Security Onion ISO image or did you install some other flavor of Ubuntu and then add our software on top of that?

Directly using your ISO downloaded from GitHub Release.

> Do you have full outbound Internet access or do you have a firewall or some other device that is doing blocking and/or packet inspection?

Yes, of course.

**Comment by dougburks** [comment]
> Directly using your ISO downloaded from GitHub Release.

I'm fairly confident that if you install our current ISO image and run through Setup, logs should make it into the Elastic stack with no further configuration necessary.

> Yes, of course.

I'm not sure which option you're saying `yes` to, but I'll assume that you have some kind of firewall.  If so, you may need to check if it is blocking any of your update traffic.

If you have further questions or problems, please use the mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
